const DISPLAY_ALERT = "DISPLAY_ALERT";
const CLEAR_ALERT = "CLEAR_ALERT";
const IS_LOADING = "IS_LOADING";
const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
const LOGIN_USER_ERROR = "UPDATE_USER_ERROR";
const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
const CHANGE_PASSWORD_BEGIN = "CHANGE_PASSWORD_BEGIN";
const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";
const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
const LOGOUT_USER = "LOGOUT_USER";

export {
  DISPLAY_ALERT,
  CLEAR_ALERT,
  IS_LOADING,
  REGISTER_USER_BEGIN,
  REGISTER_USER_SUCCESS,
  REGISTER_USER_ERROR,
  LOGIN_USER_BEGIN,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_ERROR,
  LOGOUT_USER,
  UPDATE_USER_BEGIN,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_ERROR,
  CHANGE_PASSWORD_BEGIN,
  CHANGE_PASSWORD_SUCCESS,
  CHANGE_PASSWORD_ERROR,
  TOGGLE_SIDEBAR,
};
